name: tic_tac_toe
description: A premium Tic Tac Toe game with AI, multiplayer, animations, and ads.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.4.0
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.3
  google_mobile_ads: ^5.1.0
  confetti: ^0.7.0
  firebase_core: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/bgm.mp3
    - assets/Tap.mp3
    - assets/draw.mp3
    - assets/Celebration.mp3
    - assets/logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
