name: tic_tac_toe_game
description: A Tic Tac Toe game with AI and multiplayer modes.

# Flutter & Dart version
environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter assets
flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
