name: tic_tac_toe
description: A fun and interactive Tic Tac Toe game.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Game features
  audioplayers: 6.2.0
  shared_preferences: 2.4.0
  confetti: 0.8.0
  connectivity_plus: 6.1.5  # Dart 3.2 compatible

  # Ads + Firebase
  google_mobile_ads: 4.0.0
  firebase_core: 3.12.0
  firebase_analytics: 11.0.0

  # UI icons
  cupertino_icons: 1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/Tap.mp3
    - assets/Celebration.mp3
    - assets/bgm.mp3
    - assets/draw.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
