name: tic_tac_toe
description: A Tic Tac Toe Game Pro built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^1.0.1
  shared_preferences: ^2.1.1
  confetti: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bgm.mp3
    - assets/Tap.mp3
    - assets/Celebration.mp3
    - assets/draw.mp3
    - assets/logo.png
