name: tic_tac_toe
description: A Tic Tac Toe game with AI, multiplayer, sounds, and scoreboard.

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^3.1.0  # Audio support for bgm, tap, celebration sounds

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/bgm.mp3
    - assets/celebration.mp3
    - assets/tap.mp3
