name: tic_tac_toe
description: A fun and interactive Tic Tac Toe game.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.1
  shared_preferences: ^2.2.1
  confetti: ^0.7.0
  connectivity_plus: ^4.0.2
  google_mobile_ads: ^5.0.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/Tap.mp3
    - assets/Celebration.mp3
    - assets/bgm.mp3
    - assets/draw.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
